version = "3.10.7"
runner.dialect = scala3

project {
  includePaths = [
    "glob:**/hkmc2/shared/src/main/scala/hkmc2/codegen/wasm/**",
    "glob:**/hkmc2DiffTests/src/test/scala/hkmc2/WasmDiffMaker.scala"
  ]
}
align.preset = none
align.stripMargin = false
docstrings.style = SpaceAsterisk
maxColumn = 120
newlines.source = keep
rewrite.rules = [SortModifiers]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.endMarker.insertMinSpan = 20
rewrite.scala3.removeOptionalBraces = true
rewrite.trailingCommas.style = always
