name: Cpp Backend CI with Nix

on:
  pull_request:
  push:
    branches: [ mlscript ]

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run Test
        run: nix develop --command sbt compilerJVM/test