package hkmc2
package codegen

import utils.*
import hkmc2.Message.MessageContext

import scala.collection.mutable.HashMap
import scala.util.chaining.*

import hkmc2.utils.*, shorthands.*

import semantics.*
import semantics.Elaborator.{State, Ctx, ctx}

import syntax.{Keyword, Literal, Tree}

// it should be possible to cache some common constructions (End, Option) into the context
// this avoids having to rebuild the same shapes everytime they are needed

// transform Block to Block IR so that it can be instrumented in mlscript
class ReflectionInstrumenter(using State, Raise, Ctx) extends BlockTransformer(new SymbolSubst()):
  // recover `defn` for when `sym.defn` is `None`, when the definition was generated by other compiler passes
  val defnMap = HashMap[Symbol, ClsLikeDefn]()

  type ArgWrappable = Path | ValueSymbol
  type Context = HashMap[Path, Path]
  // TODO: there could be a fresh scope per function body, instead of a single one for the entire program
  val scope = Scope.empty(Scope.Cfg.default)

  def asArg(x: ArgWrappable): Arg = x match
    case p: Path => p.asArg
    case l: ValueSymbol => l.asPath.asArg

  // null and undefined are missing
  def toValue(lit: Str | Int | BigDecimal | Bool): Value =
    val l = lit match
      case i: Int => Tree.IntLit(i)
      case b: Bool => Tree.BoolLit(b)
      case s: Str => Tree.StrLit(s)
      case n: BigDecimal => Tree.DecLit(n)
    Value.Lit(l)

  extension [A, B](ls: Ls[(A => B) => B])
    def collectApply(f: Ls[A] => B): B =
      // defer applying k while prepending new elements to the list
      ls.foldRight((_: Ls[A] => B)(Nil))((headCont, tailCont) =>
        k =>
          headCont: head =>
            tailCont: tail =>
              k(head :: tail)
      )(f)

  // helpers for constructing Block

  def assign(res: Result, symName: Str = "tmp")(k: Path => Block): Block =
    // TODO: skip assignment if res: Path?
    val sym = new TempSymbol(N, symName)
    Scoped(Set(sym), Assign(sym, res, k(sym.asSimpleRef)))

  def tuple(elems: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    assign(Tuple(false, elems.map(asArg)), symName)(k)

  // isMlsFun is probably always true?
  def call(fun: Path, args: Ls[ArgWrappable], isMlsFun: Bool = true, symName: Str = "tmp")(k: Path => Block): Block =
    assign(Call(fun, args.map(asArg) ne_:: Nil)(CallMetadata(isMlsFun, false, Nil)), symName)(k)

  // helpers for instrumenting Block

  def blockMod(name: Str) = summon[State].blockSymbol.asSimpleRef.selSN(name)
  def optionMod(name: Str) = summon[State].optionSymbol.asSimpleRef.selSN(name)

  def blockCtor(name: Str, args: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    call(blockMod(name), args, true, symName)(k)
  def optionSome(arg: ArgWrappable, symName: Str = "tmp")(k: Path => Block): Block =
    call(optionMod("Some"), Ls(arg), true, symName)(k)
  def optionNone(symName: Str = "tmp")(k: Path => Block): Block =
    assign(optionMod("None"), symName)(k)

  def blockCall(name: Str, args: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    call(blockMod(name), args, symName = symName)(k)

  // linking functions defined in MLscipt

  def fnPrintCode(p: Path)(k: Block): Block =
    // discard result, we only care about side effect
    blockCall("printCode", Ls(p))(_ => k)

  def fnConcat(p1: Path, p2: Path, symName: String = "concat")(k: Path => Block): Block =
    blockCall("concat", Ls(p1, p2), symName)(k)

  // transformation helpers

  // if sym is ClassSymbol, we may need pOpt to link to the path pointing to the value of the symbol
  def transformSymbol(sym: MaybeSymbol, pOpt: Option[Path] = N, symName: Str = "sym")(k: Path => Block): Block = sym match
    case t: TermSymbol if t.defn.exists(_.sym.asClsOrMod.isDefined) =>
      transformSymbol(t.defn.get.sym.asClsOrMod.get, pOpt, symName)(k)
    // retain names to built-in functions or function definitions
    case t: TermSymbol if t.defn.exists(_.k == syntax.Fun) =>
      blockCtor("Symbol", Ls(toValue(sym.nme)), symName)(k)
    case clsSym: ClassSymbol if ctx.builtins.virtualClasses(clsSym) =>
      blockCtor("VirtualClassSymbol", Ls(toValue(sym.nme)), symName)(k)
    case baseSym: BaseTypeSymbol =>
      val name = scope.allocateOrGetName(baseSym)
      val (owner, bsym, paramsOpt, auxParams) = (baseSym.defn, defnMap.get(baseSym)) match
        case (S(defn), _) => (defn.owner, defn.bsym, defn.paramsOpt, defn.auxParams)
        case (_, S(defn: ClsLikeDefn)) => (defn.owner, defn.sym, defn.paramsOpt, defn.auxParams)
        // FIXME: hack to patch in staging for returning the object Unit.
        case _ if baseSym == State.unitSymbol => (N, baseSym, N, Nil)
        case _ =>
          raise(ErrorReport(msg"Unable to infer parameters from symbol in staged module, which are necessary to reconstruct class instances: ${sym.toString()}" -> baseSym.toLoc :: Nil))
          return End()

      val path: ArgWrappable = pOpt.getOrElse(owner match
        case S(owner) => owner.asThis.selSN(sym.nme)
        case N => bsym.asBlkMember.get.asMemberRef(baseSym.asClsOrMod.get))
      baseSym match
        case _: ClassSymbol =>
          transformParamsOpt(paramsOpt): paramsOpt =>
            auxParams.map(ps => transformParamList(ps)).collectApply: auxParams =>
              tuple(auxParams): auxParams =>
                blockCtor("ConcreteClassSymbol", Ls(toValue(name), path, paramsOpt, auxParams), symName)(k)
        case _: ModuleOrObjectSymbol =>
          blockCtor("ModuleSymbol", Ls(toValue(name), path), symName)(k)
    case NoSymbol =>
      blockCtor("NoSymbol", Nil, symName)(k)
    case sym: LocalVarSymbol =>
      val name = scope.allocateOrGetName(sym)
      blockCtor("Symbol", Ls(toValue(name)), symName)(k)
    // preserve names to builtin symbols
    case _: BuiltinSymbol =>
      blockCtor("Symbol", Ls(toValue(sym.nme)), symName)(k)
    // FIXME: there may be more types of symbols that need to be renamed during staging
    case _ =>
      blockCtor("Symbol", Ls(toValue(sym.nme)), symName)(k)

  def transformOption[A](xOpt: Opt[A], f: A => (Path => Block) => Block)(k: Path => Block): Block = xOpt match
    case S(x) => f(x)(optionSome(_)(k))
    case N => optionNone()(k)

  // instrumentation rules

  def ruleEnd(symName: String = "end")(k: Path => Block): Block =
    blockCtor("End", Ls(), symName)(k)

  def ruleBranches(x: Path, p: Path, arms: Ls[Case -> Block], dflt: Opt[Block], symName: String = "branches")(using Context)(k: (Path, Context) => Block): Block =
    def applyRuleBranch(cse: Case, block: Block)(f: Path => Context => Block)(ctx: Context): Block =
      transformCase(cse): cse =>
        transformBlock(block)(using ctx.clone() += p -> x): (y, ctx) =>
          blockCtor("Arm", Ls(cse, y)): cde =>
            f(cde)(ctx.clone() -= p)

    (arms.map(applyRuleBranch).collectApply(_: Ls[Path] => Context => Block)(summon)): arms =>
      ctx =>
        tuple(arms): arms =>
          ruleEnd(): e =>
            // TODO: use transformOption here
            def dfltStaged(k: (Path, Context) => Block) =
              dflt match
                case S(dflt) =>
                  transformBlock(dflt)(using ctx.clone() += p -> x): (dflt, ctx) =>
                    optionSome(dflt)(k(_, ctx.clone() -= p))
                case N => optionNone()(k(_, ctx))
            dfltStaged: (dflt, ctx) =>
              blockCtor("Match", Ls(x, arms, dflt, e), symName)(k(_, ctx))

  // transformations of Block

  def transformPath(p: Path)(using ctx: Context)(k: Path => Block): Block =
    // rulePath
    ctx.get(p).map(k).getOrElse:
      p match
        case Value.SimpleRef(l) =>
          transformSymbol(l): sym =>
            blockCtor("ValueSimpleRef", Ls(sym), "var")(k)
        case Value.MemberRef(bms, disamb) =>
          transformSymbol(disamb): sym =>
            blockCtor("ValueMemberRef", Ls(sym), "var")(k)
        case l: Value.Lit =>
          blockCtor("ValueLit", Ls(l), "lit")(k)
        case s @ Select(p, Tree.Ident(name)) =>
          transformPath(p): x =>
            val sym = s.symbol.map(transformSymbol(_, S(s)))
              .getOrElse(blockCtor("Symbol", Ls(toValue(name))))
            sym: sym =>
              blockCtor("Select", Ls(x, sym), "sel")(k)
        case DynSelect(qual, fld, arrayIdx) =>
          transformPath(qual): x =>
            transformPath(fld): y =>
              blockCtor("DynSelect", Ls(x, y, toValue(arrayIdx)), "dynsel")(k)
        case _: Value.This =>
          raise(ErrorReport(msg"Value.This not supported in staged module." -> p.toLoc :: Nil))
          End()

  def transformResult(r: Result)(using Context)(k: Path => Block): Block = r match
    case p: Path => transformPath(p)(k)
    case Tuple(mut, elems) =>
      assert(!mut, "mutable tuple not supported")
      transformArgs(elems): xs =>
        tuple(xs.map(_._1)): codes =>
          blockCtor("Tuple", Ls(codes), "tup")(k)
    case Instantiate(mut, cls, argss) =>
      assert(!mut, "mutable instantiation not supported")
      argss match
        case Nil =>
          raise(ErrorReport(msg"Instantiate with no argument lists not supported in staged module." -> r.toLoc :: Nil))
          End()
        case args :: Nil =>
          transformArgs(args): xs =>
            transformPath(cls): cls =>
              tuple(xs.map(_._1)): codes =>
                blockCtor("Instantiate", Ls(cls, codes), "inst")(k)
        case args :: restArgss =>
          raise(ErrorReport(msg"Instantiate with multiple argument lists not supported in staged module." -> r.toLoc :: Nil))
          End()
    // desugar Runtime.Tuple.get into Select
    case Call(fun, Ls(Arg(_, scrut), Arg(_, Value.Lit(Tree.IntLit(idx)))) :: _) if fun == Value.SimpleRef(State.runtimeSymbol).selSN("Tuple").selSN("get") =>
      transformPath(Select(scrut, Tree.Ident(idx.toString()))(N)(false))(k)
    case Call(fun, argss) =>
      val stagedFunPath = fun match
        case s @ Select(qual, Tree.Ident(name)) => s.symbol.flatMap({
            case t: TermSymbol => t.owner.flatMap({ case sym: DefinitionSymbol[?] =>
                sym.defn.flatMap(_.hasStagedModifier.map(_ =>
                  Select(qual, Tree.Ident(name + "_gen"))(N)(false)
                ))
              })
            case _ => N
          })
        case _ => N

      argss match
        case args :: Nil =>
          val newFun = stagedFunPath.getOrElse(fun)
          transformPath(newFun): fun =>
            transformArgs(args): args =>
              tuple(args.map(_._1)): tup =>
                blockCtor("Call", Ls(fun, tup), "app")(k)
        case args :: restArgss =>
          raise(ErrorReport(msg"Call with multiple argument lists not supported in staged module." -> r.toLoc :: Nil))
          End()
    case _ =>
      raise(ErrorReport(msg"Other Results not supported in staged module: ${r.getClass.toString()}" -> r.toLoc :: Nil))
      End()

  def transformArg(a: Arg)(using Context)(k: ((Path, Bool)) => Block): Block =
    val Arg(spread, value) = a
    if spread.isDefined then
      raise(ErrorReport(msg"Spread parameters are not supported in staged module: ${a.toString()}" -> N :: Nil))
      End()
    else
      transformPath(value): value =>
        blockCtor("Arg", Ls(value)): cde =>
          k(cde, spread.isDefined)

  def transformArgs(args: Ls[Arg])(using Context)(k: Ls[(Path, Bool)] => Block): Block =
    args.map(transformArg).collectApply(k)

  def transformParamList(ps: ParamList)(k: Path => Block) =
    ps.params.map(p => transformSymbol(p.sym)).collectApply(tuple(_)(k))

  def transformParamsOpt(pOpt: Opt[ParamList])(k: Path => Block) =
    transformOption(pOpt, transformParamList)(k)

  def transformCase(cse: Case)(using Context)(k: Path => Block): Block = cse match
    case Case.Lit(lit) => blockCtor("Lit", Ls(Value.Lit(lit)))(k)
    case Case.Cls(cls, path) =>
      transformSymbol(cls): cls =>
        transformPath(path): path =>
          blockCtor("Cls", Ls(cls, path))(k)
    case Case.Tup(len, true) =>
      raise(ErrorReport(msg"Spread parameters are not supported in staged module: ${cse.toString()}" -> N :: Nil))
      End()
    case Case.Tup(len, false) =>
      blockCtor("Tup", Ls(toValue(len)))(k)
    case Case.Field(name, safe) =>
      raise(ErrorReport(msg"Case.Field not supported in staged module." -> name.toLoc :: Nil))
      End()

  def transformBlock(b: Block)(using Context)(k: Path => Block): Block =
    transformBlock(b)((p, _) => k(p))

  def transformBlock(b: Block)(using ctx: Context)(k: (Path, Context) => Block): Block = b match
    case Return(res) =>
      transformResult(res): x =>
        blockCtor("Return", Ls(x), "return")(k(_, ctx))
    case Assign(x, r, b) =>
      transformResult(r): y =>
        transformSymbol(x): xSym =>
          blockCtor("ValueSimpleRef", Ls(xSym)): xStaged =>
            (Assign(x, xStaged, _)):
              given Context = x match
                case NoSymbol => ctx.clone()
                case x: ValueSymbol => ctx.clone() += x.asPath -> xStaged
              transformBlock(b): (z, ctx) =>
                blockCtor("Assign", Ls(xSym, y, z), "assign")(k(_, ctx))
    case assign @ AssignField(lhs, nme, r, rest) =>
      // TODO: Improve. This is a kludge to allow private field initialization in modules;
      //    Ideally, we should just properly reflect these as the private field assignments they are
      assign.symbol match
        case S(ts: TermSymbol) if ts.isPrivate =>
          transformResult(r): y =>
            transformSymbol(ts): xSym =>
              blockCtor("ValueSimpleRef", Ls(xSym)): xStaged =>
                // * Reflect the binding as the private field assignment it is, so the
                // * owned field symbol is selected on its owner rather than emitted as a
                // * plain reference (which would otherwise reach `JSBuilder`'s owned-`SimpleRef` path).
                ((cont: Block) => AssignField(lhs, nme, xStaged, cont)(S(ts))):
                  given Context = ctx.clone() += Select(lhs, nme)(S(ts))(false) -> xStaged
                  transformBlock(rest): (z, ctx) =>
                    blockCtor("Assign", Ls(xSym, y, z), "assign")(k(_, ctx))
        case _ =>
          raise:
            ErrorReport(msg"Field assignment is not supported in staged modules: ${nme.name}" -> N :: Nil)
          End()
    case Define(cls: ClsLikeDefn, rest) =>
      assert(cls.companion.isEmpty, "nested module not supported")
      transformBlock(rest): p =>
        transformSymbol(cls.isym): c =>
          // staging the methods within the module
          cls.methods.map(transformFunDefn).collectApply: methods =>
            tuple(methods): methods =>
              optionNone(): none => // TODO: handle companion object
                blockCtor("ClsLikeDefn", Ls(c, methods, none)): cls =>
                  blockCtor("Define", Ls(cls, p))(k(_, ctx))
    case Define(v: ValDefn, rest) =>
      // TODO: only allow ValDefn inside ctors
      transformBlock(rest): p =>
        transformOption(v.tsym.owner, transformSymbol(_)): owner =>
          transformSymbol(v.sym): sym =>
            transformPath(v.rhs): rhs =>
              blockCtor("ValDefn", Ls(owner, sym, rhs)): v =>
                blockCtor("Define", Ls(v, p))(k(_, ctx))
    case End(_) => ruleEnd()(k(_, ctx))
    case Match(p, ks, dflt, rest) =>
      transformPath(p): x =>
        ruleBranches(x, p, ks, dflt): (stagedMatch, ctx) =>
          transformBlock(rest)(using ctx): (z, ctx) =>
            fnConcat(stagedMatch, z, "match")(k(_, ctx))
    case Begin(sub, rest) =>
      // TODO: This is untested as there is no test case that generates the Begin block yet
      transformBlock(sub): (sub, ctx) =>
        transformBlock(rest)(using ctx): (rest, ctx) =>
          fnConcat(sub, rest)(k(_, ctx))
    case Scoped(syms, body) =>
      syms.toList.sortBy(_.uid).map(transformSymbol(_)).collectApply: symsStaged =>
        tuple(symsStaged): tup =>
          transformBlock(body): (body, ctx) =>
            blockCtor("Scoped", Ls(tup, body))(b => Scoped(syms, k(b, ctx)))
    case Define(_: FunDefn, _) =>
      raise(ErrorReport(msg"Nested function definitions are not supported in staged modules. Try enabling :ftc." -> N :: Nil))
      End()
    case _: Label | _: Break =>
      raise(ErrorReport(msg"Other Blocks not supported in staged module: ${b.getClass.toString()}." -> N :: Nil))
      End()
    case _ =>
      raise(ErrorReport(msg"Other Blocks not supported in staged module: ${b.getClass.toString()}" -> N :: Nil))
      End()

  def transformFunDefn(f: FunDefn)(using Context)(k: Path => Block): Block =
    transformBlock(f.body): body =>
      if f.params.length != 1 then
        raise(ErrorReport(msg":ftc must be enabled to desugar functions with multiple parameter lists." -> f.sym.toLoc :: Nil))
      // maintain parameter names in instrumented code
      f.params.map(
        _.params.map(p => blockCtor("Symbol", Ls(toValue(p.sym.nme)))).collectApply
      ).collectApply: paramListSyms =>
        blockCtor("Symbol", Ls(toValue(f.sym.nme))): sym =>
          paramListSyms.map(tuple(_)).collectApply: tups =>
            tuple(tups): tup =>
              blockCtor("FunDefn", Ls(sym, tup, body, toValue(true)))(k)

  def applyFunDefnInner(f: FunDefn): (FunDefn, Block => Block) =
    val genSymName = f.sym.nme + "_instr"
    val genSym = BlockMemberSymbol(genSymName, Nil, false)
    val sym = f.owner.get.asThis.selSN(genSymName)

    // turn into fundefn
    val dSym = TermSymbol(f.dSym.k, f.dSym.owner, Tree.Ident(f.sym.nme + "_instr"))
    val argSyms = f.params.flatMap(_.params).map(_.sym)
    val newBody = Scoped(Set(argSyms*), transformFunDefn(f)(using new HashMap)(Return(_)))

    // TODO: remove it. only for test
    val debug = (k: Block) => call(sym, Nil)(fnPrintCode(_)(k))
    val newFun = f.copy(sym = genSym, dSym = dSym, params = Ls(PlainParamList(Nil)), body = newBody)(f.configOverride, f.annotations)
    (newFun, debug)

  override def applyBlock(b: Block): Block = super.applyBlock(b) match
    // find modules with staged annotation
    case Define(c: ClsLikeDefn, rest) if c.companion.exists(_.isStaged) =>
      val sym = c.sym.subst
      val companion = c.companion.get
      val (stagedMethods, debugPrintCode) = companion.methods
        .map(applyFunDefnInner)
        .unzip
      val ctor = FunDefn.withFreshSymbol(S(companion.isym), BlockMemberSymbol("ctor$", Nil), Ls(PlainParamList(Nil)), companion.ctor)(N, Nil)
      val (stagedCtor, ctorPrint) = applyFunDefnInner(ctor)

      val debugBlock = (ctorPrint :: debugPrintCode)
        .foldRight(End(): Block)(_(_))
      def debugCont(rest: Block) =
        Begin(debugBlock, rest)
      // add generator functions for classes within the constructor
      val genCls = new BlockTransformer(SymbolSubst.Id):
        override def applyBlock(b: Block): Block = super.applyBlock(b) match
          case Define(c: ClsLikeDefn, rest) if c.companion.isEmpty =>
            val (stagedMethods, debugPrintCode) = c.methods
              .map(applyFunDefnInner)
              .unzip
            val newModule = c.copy(methods = c.methods ++ stagedMethods)(c.configOverride, c.annotations.filter:
              case Annot.Modifier(Keyword.`staged`) => false
              case _ => true)
            Define(newModule, rest)
          case b => b
      val newCtor = genCls.applyBlock(companion.ctor)
      val newCompanion = companion.copy(
        methods = stagedCtor :: companion.methods ++ stagedMethods,
        ctor = Begin(newCtor, debugCont(End())),
      )
      val newModule = c.copy(sym = sym, companion = S(newCompanion))(c.configOverride, c.annotations.filter:
        case Annot.Modifier(Keyword.`staged`) => false
        case _ => true)
      Define(newModule, rest)
    case b => b

  def mkDefnMap(b: Block): Unit =
    val transformer = new BlockTraverser:
      override def applyDefn(defn: Defn) = defn match
        case c: ClsLikeDefn =>
          defnMap.addOne(c.isym, c)
          super.applyDefn(defn)
        case _ => super.applyDefn(defn)
    transformer.applyBlock(b)

  def apply(b: Block) =
    mkDefnMap(b)
    applyBlock(b)
